
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",

        // PRODUCT
        PRODUCT_VIEW : "PRODUCT_VIEW",
        PRODUCT_ADD_NEW : "PRODUCT_ADD_NEW",
        PRODUCT_EDIT : "PRODUCT_EDIT",

        // CATEGORY
        CATEGORY_ADD_NEW : "CATEGORY_ADD_NEW",
        CATEGORY_EDIT : "CATEGORY_EDIT",

        // SUPPLY 
        SUPPLY_VIEW : "SUPPLY_VIEW",
        SUPPLY_EDIT : "SUPPLY_EDIT",

        // SUPPLIER
        SUPPLIER_VIEW : "SUPPLIER_VIEW",
        SUPPLIER_ADD_NEW : "SUPPLIER_ADD_NEW",
        SUPPLIER_EDIT : "SUPPLIER_EDIT",

        // PEOPLE
        USER_VIEW : "USER_VIEW",
        USER_ADD_NEW : "USER_ADD_NEW",
        USER_EDIT : "USER_EDIT",

        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
        PRODUCT_FILTER : "PRODUCT_FILTER",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
        PRODUCT_DELETE : "PRODUCT_DELETE",
        CATEGORY_DELETE : "CATEGORY_DELETE",
        SUPPLY_DELETE : "SUPPLY_DELETE",
        SUPPLIER_DELETE : "SUPPLIER_DELETE",
        USER_DELETE : "USER_DELETE",
    },
});
